# Generated by Django 5.2.8 on 2025-11-28 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_mone',
            field=models.PositiveIntegerField(default=12),
            preserve_default=False,
        ),
    ]
