# Generated by Django 5.2.8 on 2025-11-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reqmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinusd',
            name='price',
            field=models.DecimalField(decimal_places=8, max_digits=20),
        ),
    ]
